SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-01-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-01-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-02-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-02-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-03-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-03-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-04-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-04-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-05-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-05-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-06-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-06-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-07-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-07-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-08-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-08-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-09-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-09-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-10-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-10-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-11-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-11-01'))) AS DAYS
UNION ALL
SELECT
	MONTHNAME(DATE_FORMAT(NOW() , '%Y-12-01')) AS MONTH_NUM ,
	DAY(LAST_DAY(DATE_FORMAT(NOW() , '%Y-12-01'))) AS DAYS;